### PR TITLE
Create vrs subdirectory and vrs_readme_marten.txt

### PR DESCRIPTION
**Pull request by matren395**
Creating a subdirectory to host all work for the Global Alliance For Genomics and Health (GA4GH) Variant Representation Specification (VRS) Project ([read more at the wiki here](https://vrs.ga4gh.org/en/stable/introduction.html)) for adding universal allele IDs to gnomAD variants and allele data. 

Will soon add a script for creating a test dataset - and potentially said test dataset - here!

### CODE REVIEW

**Review by ch-kr — COMMENTED** [review]
great idea adding a readme! one small comment is it might be helpful to add a link to the GA4GH website explaining VRS

**Comment by matren395** [comment]
Just added, let me know if it's a bit clearer now

**Comment by ch-kr** [comment]
sorry, I don't see the change -- have you pushed it?

**Review by ch-kr — APPROVED** [review]
LGTM

**Pull request merged**
